### PR TITLE
fix: remove unused hooks on setting

### LINKED ISSUE #39: removed hooks are not deleted
<del>I see `commit-msg` hook is supported, but I tried like following and failed:</del>

```js
module.exports = {
  'pre-commit': 'npx lint-staged',
  'commit-msg': 'npx commitlint -e', // it will work
}
```

### PR DESCRIPTION
**Pull request by JounQin**
close #39

### CODE REVIEW

**Comment by JounQin** [comment]
@toplenboren Hi, any luck to review?

**Comment by toplenboren** [comment]
Hi! Gonna review on weekends

**Review by toplenboren — APPROVED** [review]
Thanks! Gonna release it in 2.2.1

**Comment by JounQin** [comment]
@toplenboren Hi, what is the schedule to merge and release?

**Comment by toplenboren** [comment]
Live in 2.3.0, Thanks!

**Pull request merged**
