### PR TITLE
fix: skip if no .git root folder found

### LINKED ISSUE #80: It should skip installation if no `.git` folder found
```shell
11:12:42.567 | $ simple-git-hooks && yarn-deduplicate --strategy fewer \|\| exit 0
11:12:42.655 | [ERROR], Was not able to set git hooks. Error: Error: ENOENT: no such file or directory, mkdir 'undefined/hooks/'
```

### PR DESCRIPTION
**Pull request by JounQin**
close #80

### CODE REVIEW

**Review by toplenboren — APPROVED** [review]

**Comment by toplenboren** [comment]
looks good, merge it when ready =)

**Comment by JounQin** [comment]
@toplenboren Just found I forgot to add `return` statement, it should be ready now?

**Comment by n0th1ng-else** [comment]
I just faced the same issue. looking forward to have the fix released 🙏🏿

**Comment by toplenboren** [comment]
Hi, just published https://www.npmjs.com/package/simple-git-hooks/v/2.8.1 with this fix

@JounQin @n0th1ng-else

@JounQin thanks for this fix :-)

**Comment by cuebit** [comment]
Will there be a release tag created for this?

**Pull request merged**
