### PR TITLE
Simple pre commit -> simple git hooks : WiP

### LINKED ISSUE #14: Other hook support
Maybe I made a mistake by suggesting only `pre-commit` hook support. We can add other hook support, but it will require the project to change the name (`simple-hooks`?).

We can have the same one-line config for `pre-commit`:

```json
  "simple-hooks": "npx lint-staged"
```

And object for custom hooks:

```json
  "simple-hooks": {
    "pre-push": "npx x"
  }
```

### PR DESCRIPTION
**Pull request by toplenboren**
* Rename the package to simple-git-hooks
* Add an ability to add other git hooks 

Fixes #14

### CODE REVIEW

**Comment by ai** [comment]
😍

**Comment by Kikobeats** [comment]
@toplenboren one question there: in case of commands like `commit-msg` that can receive a parameter, how the parameter needs to be provided?

Specifically, I want to know how to convert this

```json
{
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  }
}
```

into something that `simple-git-hooks` can understand 🙂

**Comment by toplenboren** [comment]
> @toplenboren one question there: in case of commands like `commit-msg` that can receive a parameter, how the parameter needs to be provided?
> 
> Specifically, I want to know how to convert this
> 
> ```json
> {
>   "husky": {
>     "hooks": {
>       "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
>     }
>   }
> }
> ```
> 
> into something that `simple-git-hooks` can understand 🙂

It should work as is.

When run `npx simple-git-hooks` package just gets the list of hooks from config, then sets up a bunch of `{hook_name}.sh` files under `.git/hooks` directory

So if you write in package.json something for e.g:

`simple-git-hooks: {"commit-msg": "commitlint -E anything"} it would simply create the `.git/hooks/commit-msg.sh` file with contents:

```
#bin/bash

commitlint -E anything
```

So I think it should work as is.

> However, I spotted you are using HUSKY_GIT_PARAMS. This package does not have the alike functionaluty. You might want to explicitly set commitlint arguments

**Comment by Kikobeats** [comment]
you're right, thanks for the reply!

Migrating all my things to `simple-git-hooks` 🙂

**Comment by ml242** [comment]
@Kikobeats - i created this issue because my project does not seem to behave properly, did you ever figure this out?

https://github.com/toplenboren/simple-git-hooks/issues/71

**Pull request merged**
