### PR TITLE
Add support for pnpm

### LINKED ISSUE #41: Can't install with pnpm
```
node_modules/.pnpm/simple-git-hooks@2.2.0/node_modules/simple-git-hooks: Running postinstall script, failed in 126ms
.../node_modules/simple-git-hooks postinstall$ node ./postinstall.js
│ internal/fs/utils.js:307
│     throw err;
│     ^
│ Error: ENOENT: no such file or directory, stat 'D:\Projects\vue-promise-dialogs\node_modules\.pnpm\simple-git-hooks@2.2.0\package.json'
│     at Object.statSync (fs.js:1086:3)
│     at _getPackageJson (D:\Projects\vue-promise-dialogs\node_modules\.pnpm\simple-git-hooks@2.2.0\node_modules\simple-git-hooks\simple-git-hooks.js:140:13)
│     at checkSimpleGitHooksInDependencies (D:\Projects\vue-promise-dialogs\node_modules\.pnpm\simple-git-hooks@2.2.0\node_modules\simple-git-hooks\simple-git-hooks
│     at postinstall (D:\Projects\vue-promise-dialogs\node_modules\.pnpm\simple-git-hooks@2.2.0\node_modules\simple-git-hooks\postinstall.js:15:9)
│     at Object.<anonymous> (D:\Projects\vue-promise-dialogs\node_modules\.pnpm\simple-git-hooks@2.2.0\node_modules\simple-git-hooks\postinstall.js:24:1)
│     at Module._compile (internal/modules/cjs/loader.js:1063:30)
│     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
│     at Module.load (internal/modules/cjs/loader.js:928:32)
│     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
│     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
│   errno: -4058,
│   syscall: 'stat',
│   code: 'ENOENT',
│   path: 'D:\\Projects\\vue-promise-dialogs\\node_modules\\.pnpm\\simple-git-hooks@2.2.0\\package.json'
│ }
└─ Failed in 127ms
 ERROR  Command failed with exit code 1.
 ```

pnpm version: 5.18.7

### PR DESCRIPTION
**Pull request by Djaler**
Fixes #41

### CODE REVIEW

**Comment by toplenboren** [comment]
Hey, thank you for the PR!

Gonna review it on weekends!

**Comment by Djaler** [comment]
Just a reminder

**Review by toplenboren — APPROVED** [review]

**Comment by toplenboren** [comment]
Thanks! Gonna release this feature in 2.3.0

**Comment by toplenboren** [comment]
Live in 2.3.0, Thanks!

**Pull request merged**
